### ISSUE TITLE
Crashes if ruuvi is in wrong data format

### ISSUE THREAD

**Issue by HakonMellbye** [rroemhild/micropython-ruuvitag#6]
So it seems like there is an issue when the ruuvitag is in not in RAW mode.
This code fails if a ruuvi is in URL Mode
```
### Ruuvi example code
def simple_ruuvi():
    rts = RuuviTagScanner()
    for ruuvitag in rts.find_ruuvitags(timeout=10):
        print(ruuvitag)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "system_functions.py", line 93, in simple_ruuvi
  File "/flash/lib/ruuvitag/scanner.py", line 47, in find_ruuvitags
  File "/flash/lib/ruuvitag/__init__.py", line 59, in get_tag
  File "/flash/lib/ruuvitag/__init__.py", line 85, in get_data
  File "/flash/lib/ruuvitag/__init__.py", line 128, in get_data_format_raw
TypeError: 'NoneType' object is not subscriptable

**Comment by rroemhild** [comment]
Hi @HakonMellbye, I need to flash one of my RuuviTag with an old firmware to get into this. Since URL mode is deprecated and replaced by RAWv2 mode (data format 5), I think about to drop URL support. Do you need URL support for your project?

**Comment by rroemhild** [comment]
I found a Tag with an older firmware which has data format 4 but can not reproduce your error. Do you now the firmware version installed on your RuuviTag? What is the URL the RuuviTag publishes? It could also be a problem with another Bluetooth devices where the code is not able to get the manufacturer data.

Try to whitelist your tag mac address, this should ignore all other devices.

**Comment by rroemhild** [comment]
Got it. RuuvTag in BootMode throws this exception. Fixed in develop branch. Thank you for reporting this issue.

**Comment by HakonMellbye** [comment]
Thank you for the help.
